"use strict";
let strJS = 'any string';
let strTS = 'any string';
let numJS = 123;
let numTS = 123;
let boolJS = true;
let boolTS = true;
let anyType;
anyType = 1;
anyType = 'str';
anyType = true;
anyType = [];
anyType = {};
let strNumType;
strNumType = 'str';
strNumType = 123;
let strNumTypeBool;
strNumTypeBool = 'str';
strNumTypeBool = 123;
strNumTypeBool = true;
